name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Clean install dependencies
        run: yarn install --frozen-lockfile

      - name: Run deploy script
        run: |
          git config user.name "Shaun" && git config user.email "ayy@nope.com"
          npm run gh-pages-deploy
